// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHjtQlyHvoCRIHN95zn27v74RQfFyBuO8',
    appId: '1:763198706122:ios:5be4ea080a42140ee7ff33',
    messagingSenderId: '763198706122',
    projectId: 'social-media-1518d',
    storageBucket: 'social-media-1518d.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBktKbrW-4Kvwp0BmwJHno9usLB2BUmnx8',
    appId: '1:763198706122:web:0ef4f42285ca2517e7ff33',
    messagingSenderId: '763198706122',
    projectId: 'social-media-1518d',
    authDomain: 'social-media-1518d.firebaseapp.com',
    storageBucket: 'social-media-1518d.appspot.com',
    measurementId: 'G-LNE6N3BNSK',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBktKbrW-4Kvwp0BmwJHno9usLB2BUmnx8',
    appId: '1:763198706122:web:0ef4f42285ca2517e7ff33',
    messagingSenderId: '763198706122',
    projectId: 'social-media-1518d',
    authDomain: 'social-media-1518d.firebaseapp.com',
    storageBucket: 'social-media-1518d.appspot.com',
    measurementId: 'G-LNE6N3BNSK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHjtQlyHvoCRIHN95zn27v74RQfFyBuO8',
    appId: '1:763198706122:ios:5be4ea080a42140ee7ff33',
    messagingSenderId: '763198706122',
    projectId: 'social-media-1518d',
    storageBucket: 'social-media-1518d.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtB0b42auzUk_OFLNiFIpRcvduNhlWNpA',
    appId: '1:763198706122:android:b6437e24ceccfa36e7ff33',
    messagingSenderId: '763198706122',
    projectId: 'social-media-1518d',
    storageBucket: 'social-media-1518d.appspot.com',
  );

}